### ISSUE TITLE
problem in compiling mapsifter

### ISSUE THREAD

**Issue by lmanchon** [smithlabcode/utils#2]
--Hi,

something wrong in compiling mapsifter.cpp

g++ -Wall -fPIC -std=c++0x -fmessage-length=50 -o mapsifter mapsifter.cpp ../smithlab_cpp/GenomicRegion.o ../smithlab_cpp/smithlab_os.o ../smithlab_cpp/smithlab_utils.o ../smithlab_cpp/OptionParser.o -I../smithlab_cpp/

mapsifter.cpp:38:12: error: ‘std::tr1’ has
   not been declared
 using std::tr1::unordered_map;
            ^
mapsifter.cpp: In function ‘void sift(const
   std::vector<GenomicRegion>&, bool, bool,
   std::vector<GenomicRegion>&)’:
mapsifter.cpp:105:3: error: ‘unordered_map’
   was not declared in this scope
   unordered_map<string, size_t> chrom_lookup;
   ^
mapsifter.cpp:105:3: note: suggested alternative:
In file included from /tools/compilers/gcc/4.9.1/include/c++/4.9.1/unordered_map:48:0,
                 from ../smithlab_cpp/smithlab_os.hpp:29,
                 from ../smithlab_cpp/GenomicRegion.hpp:28,
                 from mapsifter.cpp:27:
/tools/compilers/gcc/4.9.1/include/c++/4.9.1/bits/unordered_map.h:98:11: note:
    ‘std::unordered_map’
     class unordered_map
           ^
mapsifter.cpp:105:23: error: expected
   primary-expression before ‘,’ token
   unordered_map<string, size_t> chrom_lookup;
                       ^
mapsifter.cpp:105:31: error: expected
   primary-expression before ‘>’ token
   unordered_map<string, size_t> chrom_lookup;
                               ^
mapsifter.cpp:105:33: error: ‘chrom_lookup’
   was not declared in this scope
   unordered_map<string, size_t> chrom_lookup;
                                 ^
mapsifter.cpp:116:11: error: ‘unordered_map’
   does not name a type
     const unordered_map<string, size_t>::const_it
           ^
mapsifter.cpp:118:9: error: ‘j’ was not
   declared in this scope
     if (j != chrom_lookup.end()) {
         ^

is there a way to correct that ?

thank you  --

**Comment by andrewdavidsmith** [comment]
Sorry for not noticing this previously. the error is associated with compiler versions, and the fact that c++11 doesn't have unordered_map in tr1, but rather part of std. I will create a separate issue to fix this in all places where it is happening.
